#!/bin/sh
#${0%/*}/erlsame plbweb -eval "make:all(), application:ensure_all_started(plbweb)"
LD_LIBRARY_PATH=$(apl --show_src_dir)/.libs ${0%/*}/erlsame plbweb 'posteval:make:all().' 'posteval:plbinets:acquire().'
